# Generated by Django 2.1.5 on 2019-03-18 22:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('forename', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='Coach', max_length=100)),
                ('age', models.IntegerField(default=None)),
                ('experience', models.IntegerField(default=None)),
                ('bio', models.TextField(default='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(blank=True, default='', max_length=100)),
                ('eventDate', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.CharField(blank=True, default='', max_length=100)),
                ('homeFighter', models.CharField(blank=True, default='', max_length=100)),
                ('homeClub', models.CharField(blank=True, default='', max_length=100)),
                ('awayFighter', models.CharField(blank=True, default='', max_length=100)),
                ('awayClub', models.CharField(blank=True, default='', max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
                ('credit', models.CharField(blank=True, default='', max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='subtitle', max_length=200)),
                ('text', models.TextField(default='')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, default='Boxer', max_length=20)),
                ('age', models.IntegerField(default=16)),
                ('fights', models.IntegerField(default=1)),
                ('hometown', models.CharField(default='Alloa', max_length=90)),
                ('first_title', models.CharField(blank=True, default='', max_length=100)),
                ('second_title', models.CharField(blank=True, default='', max_length=100)),
                ('third_title', models.CharField(blank=True, default='', max_length=100)),
                ('fourth_title', models.CharField(blank=True, default='', max_length=100)),
                ('sixth_title', models.CharField(blank=True, default='', max_length=100)),
                ('seventh_title', models.CharField(blank=True, default='', max_length=100)),
                ('eighth_title', models.CharField(blank=True, default='', max_length=100)),
                ('ninth_title', models.CharField(blank=True, default='', max_length=100)),
                ('tenth_title', models.CharField(blank=True, default='', max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
