# Generated by Django 2.1.5 on 2019-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
