# Generated by Django 2.1.5 on 2019-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_coach_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.IntegerField(default=None),
        ),
    ]
