# Generated by Django 2.1.5 on 2019-03-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='author',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
