# Generated by Django 2.1.5 on 2019-05-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190319_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='author',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
