# Generated by Django 2.0.10 on 2019-02-25 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190207_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(default='Boxer', max_length=20)),
                ('age', models.IntegerField(default=16)),
                ('titles', models.TextField(default='')),
                ('picture', models.ImageField(default='blog/static/media/default.jpg', upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
