# Generated by Django 2.0.10 on 2019-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
