# Generated by Django 2.0.10 on 2019-02-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile_fights'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(default='Alloa', max_length=90),
        ),
    ]
