# Generated by Django 2.0.10 on 2019-02-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_hometown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
