# Generated by Django 2.0.10 on 2019-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190227_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
