# Generated by Django 2.0.10 on 2019-02-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190227_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='titles',
        ),
    ]
